# -*- coding: utf-8 -*-
"""01_basics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n9HOLfwtX2j6BIU0tbc1sC0QfW9_jEMt

# 01_basics

# 00_joke_bot.md
"""

# Constants for the program
PROMPT = "What do you want? "
JOKE = """Here is a joke for you!
Panaversity GPT - Sophia is heading out to the grocery store.
A programmer tells her: get a liter of milk, and if they have eggs, get 12.
Sophia returns with 13 liters of milk. The programmer asks why and Sophia replies: 'because they had eggs'"""
SORRY = "Sorry I only tell jokes"

# Main function to interact with the user
def main():
    # Prompt the user for input
    user_input = input(PROMPT)

    # Check if the user entered "Joke"
    if user_input == "Joke":
        print(JOKE)
    else:
        print(SORRY)

# This line ensures the main function is called when the script is run
if __name__ == '__main__':
    main()

"""# 01_double_it.md

"""

# Main function to interact with the user and double the number
def main():
    # Ask the user to enter a number
    curr_value = int(input("Enter a number: "))

    # Use a while loop to double the number until it's greater than or equal to 100
    while curr_value < 100:
        print(curr_value, end=" ")  # Print the current value
        curr_value *= 2  # Double the value

    # Print the final value (which is >= 100)
    print(curr_value)

# This line ensures the main function is called when the script is run
if __name__ == '__main__':
    main()

"""# 02_liftoff.md

"""

# Main function to handle the countdown and liftoff
def main():
    # Countdown from 10 to 1 using a for loop
    for i in range(10, 0, -1):
        print(i, end=" ")  # Print the current number with a space after it

    # Print Liftoff! after the countdown
    print("Liftoff!")

# This line ensures the main function is called when the script is run
if __name__ == '__main__':
    main()

"""# 03_guess_my_number.md"""

import random

def guess_number():
    secret_number = random.randint(1, 99)
    attempts = 0

    print("I'm thinking of a number between 1 and 99...")

    while True:
        try:
            guess = int(input(" Enter your guess: "))
            attempts += 1

            if guess < secret_number:
                print(" Too low! Try again.")
            elif guess > secret_number:
                print(" Too high! Try again.")
            else:
                print(f" Correct! The number was {secret_number} in {attempts} attempts.")
                break

        except ValueError:
            print("Invalid input! Please enter a number.")

if __name__ == '__main__':
    guess_number()

"""# 04_random_numbers.md

"""

import random

# Constants for the number of random numbers, and the range
N_NUMBERS: int = 10
MIN_VALUE: int = 1
MAX_VALUE: int = 100

def main():
    # Loop to generate and print N_NUMBERS random numbers
    for _ in range(N_NUMBERS):
        print(random.randint(MIN_VALUE, MAX_VALUE), end=" ")

# This line ensures the main function is called when the script is run
if __name__ == '__main__':
    main()