# -*- coding: utf-8 -*-
"""00_choosing_returns.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/188p03821iuszL83vA157RIHheW5Tkfb-

07_information_flow
# 00_choosing_returns.md
"""

# Define the ADULT_AGE constant
ADULT_AGE = 18

# Function to check if the person is an adult based on their age
def is_adult(age):
    if age >= ADULT_AGE:
        return True
    else:
        return False

# Main function to interact with the user
def main():
    # Prompt user for their age
    age = int(input("How old is this person?: "))

    # Call the is_adult function and print the result
    print(is_adult(age))

# This line ensures the main function is called when the script is run
if __name__ == '__main__':
    main()