# -*- coding: utf-8 -*-
"""03_in_stock.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m4iklO99EUFVEziTqCKWzBFbBL_X7eVq

07_information_flow
# 03_in_stock.md
"""

# Define the num_in_stock function to check inventory of a specific fruit
def num_in_stock(fruit):
    # Sample inventory dictionary with fruits and their stock numbers
    inventory = {
        "apple": 50,
        "banana": 30,
        "pear": 1000,
        "orange": 200,
        "grape": 0
    }

    # Check if the fruit is in inventory and return the stock number, otherwise return 0
    return inventory.get(fruit, 0)

# Main function to interact with the user
def main():
    # Prompt user to enter a fruit
    fruit = input("Enter a fruit: ").lower()  # Convert input to lowercase for consistency

    # Get the number of that fruit in stock
    stock = num_in_stock(fruit)

    # Check if the stock is greater than 0 and print accordingly
    if stock > 0:
        print("This fruit is in stock! Here is how many:")
        print(stock)
    else:
        print("This fruit is not in stock.")

# This line ensures the main function is called when the script is run
if __name__ == '__main__':
    main()