# -*- coding: utf-8 -*-
"""04_multiple_returns.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1twgo9UG_jXPwNA9iDhEDL4U319m-rEDJ

07_information_flow
# 04_multiple_returns.md
"""

# Function to ask for user data and return it
def get_user_data():
    # Ask for user input for first name, last name, and email address
    first_name = input("What is your first name?: ")
    last_name = input("What is your last name?: ")
    email = input("What is your email address?: ")

    # Return the collected data as a tuple
    return first_name, last_name, email

# Main function to interact with the user and display the results
def main():
    # Get user data
    user_data = get_user_data()

    # Print the received user data
    print(f"Received the following user data: {user_data}")

# This line ensures the main function is called when the script is run
if __name__ == '__main__':
    main()