# -*- coding: utf-8 -*-
"""05_subtract_7.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jUBqOAXAGXu-mZ2Nfh77B_ru7qAR36Mr

07_information_flow
# 05_subtract_7.md
"""

def main():
	num: int = 7
	num = subtract_seven(num)
	print("this should be zero: ", num)

def subtract_seven(num):
	num = num - 7
	return num


# There is no need to edit code beyond this point

if __name__ == '__main__':
    main()