2# -*- coding: utf-8 -*-
"""00_averages.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kYFWp8RRWS8IG9Qp8uIVv-TCbV39ds4P

# 06_functions
00_averages.md
"""

def average(a: float, b: float) -> float:
    """
    This function returns the average of two numbers.
    """
    return (a + b) / 2

def main():
    # Taking input from the user to make it more interactive
    try:
        num1 = float(input("Enter the first number: "))
        num2 = float(input("Enter the second number: "))

        # Call the average function
        result = average(num1, num2)

        # Print the result in a formatted way
        print(f"The average of {num1} and {num2} is {result:.2f}")

    except ValueError:
        print("Invalid input. Please enter numeric values.")

# This provided line is required at the end of the Python file
if __name__ == '__main__':
    main()