# -*- coding: utf-8 -*-
"""01_chaotic_counting.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Iej00eH9mrD8Wf6IwgEFoVF1N73NxvcC

# 06_functions
01_chaotic_counting.md
"""

import random

# Set the likelihood that counting will stop
DONE_LIKELIHOOD = 0.3  # 30% chance

def chaotic_counting():
    for i in range(1, 11):  # Counting from 1 to 10
        if done():
            return  # Stop if done() returns True
        print(i)

def done():
    """Returns True with a probability of DONE_LIKELIHOOD"""
    return random.random() < DONE_LIKELIHOOD

def main():
    print("I'm going to count until 10 or until I feel like stopping.")
    chaotic_counting()
    print("I'm done")

if __name__ == "__main__":
    main()