3# -*- coding: utf-8 -*-
"""02_count_even.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AHLwotg9E5MvZxGuZCHEM_Zn7-3kAjSg

06_functions
# 02_count_even.md
"""

def count_even(lst):
    even_count = 0
    for num in lst:
        if num % 2 == 0:  # Check if the number is even
            even_count += 1
    return even_count

def main():
    lst = []

    while True:
        try:
            # Prompt user for an integer or to press enter to stop
            user_input = input("Enter an integer or press enter to stop: ")
            if user_input == "":  # Stop if the input is empty
                break
            lst.append(int(user_input))  # Add the number to the list
        except ValueError:
            print("Please enter a valid integer.")

    # Call count_even to count the even numbers in the list
    even_count = count_even(lst)
    print(f"The number of even numbers in the list is: {even_count}")

if __name__ == "__main__":
    main()
2