# -*- coding: utf-8 -*-
"""04_double.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XGp0aaVF4Punu-h2FxRFwvxpEGSmy4ku

06_functions
# 04_double.md
"""

def double(num: int):
    return num * 2

# There is no need to edit code beyond this point

def main():
    num = int(input("Enter a number: "))
    num_times_2 = double(num)
    print("Double that is", num_times_2)

if __name__ == '__main__':
    main()