# -*- coding: utf-8 -*-
"""05_get_name.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IbHLz7aUQpcUYr3pFlz8wpt1Vg2vJ-sI

06_functions
# 05_get_name.md
"""

def get_name():
    # This function returns the name "Sophia"
    return "Sophia"

def main():
    # Retrieve the name by calling get_name
    name = get_name()

    # Print a greeting message with the name
    print("Howdy", name, "! 🤠")

# This line ensures that the main function is called when running the script
if __name__ == '__main__':
    main()