# -*- coding: utf-8 -*-
"""07_print_divisor.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iiAO3CDIxKmZCfnpz-R_dFSwodUMRHWo

06_functions
# 07_print_divisor.md
"""

def print_divisors(num):
    # Loop through numbers from 1 to num
    divisors = []
    for i in range(1, num + 1):
        if num % i == 0:  # Check if i is a divisor of num
            divisors.append(i)

    # Print the divisors
    print(f"Here are the divisors of {num}:")
    print(" ".join(map(str, divisors)))

def main():
    # Ask the user to input a number
    num = int(input("Enter a number: "))

    # Call the print_divisors function
    print_divisors(num)

if __name__ == '__main__':
    main()

# """ Another example Solve it like that to e.g 2"""

def print_divisors(num: int):
    print("Here are the divisors of", num)
    for i in range(num):
        curr_divisor = i + 1
        if num % curr_divisor == 0:
            print(curr_divisor)




# There is no need to edit code beyond this point

if __name__ == '__main__':
    main()