# -*- coding: utf-8 -*-
"""08_print_multiple.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dePUjlP92jklBknwuWrM-A6JiCqU8gZI

06_functions
# 08_print_multiple.md
"""

def print_multiple(message, repeats):
    # Print the message 'repeats' number of times
    for _ in range(repeats):
        print(message)

def main():
    # Ask the user to input a message
    message = input("Please type a message: ")

    # Ask the user to input the number of times to repeat the message
    repeats = int(input("Enter a number of times to repeat your message: "))

    # Call the print_multiple function
    print_multiple(message, repeats)

if __name__ == '__main__':
    main()

# """Another example Solve it like that to (eg 2)"""

def print_multiple(message: str, repeats: int):
    # Loop through the range of repeats to print the message multiple times
    for i in range(repeats):  # This loops `repeats` times
        print(message)

def main():
    # Prompt the user to input a message
    message = input("Please type a message: ")

    # Prompt the user to input how many times the message should be repeated
    repeats = int(input("Enter a number of times to repeat your message: "))

    # Call the function to print the message the specified number of times
    print_multiple(message, repeats)

# This line ensures that the main function is executed when the script is run directly
if __name__ == '__main__':
    main()