# -*- coding: utf-8 -*-
"""02_e=mc2.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZnyZehKj4IIFbnrxZggJ2maAeuGRZ0eJ
"""

def main():
  # speed of light constant in meters per second
  C = 299792458   # m/s

  # ask the user for mass in kilograms
  mass_in_kg = float(input("Enter kilos of mass: "))

  # calculate energy using Einstein's mass-energy equivalence formula: E = M * C^2
  energy_in_joules = mass_in_kg *(C ** 2)

  # output the results
  print("e = m * C^2...")
  print(f"m = {mass_in_kg} kg")
  print(f"C = {C} m/s")
  print(f"{energy_in_joules} joules of energy!")

  # Call the main function when the script is executed
if __name__ == "__main__":
    main()