# -*- coding: utf-8 -*-
"""03_feet_to_inches.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bN42gc6XXd9M-5QGzmApVHDJaMFwSh3e
"""

def main():
  # Ask the user for the number of feet and convert it to a float
   feet = float(input("Enter number of feet: "))

  # Perform the conversion from feet to inches
   print(f"That is {feet * 12} inches!")
  # Directly calculate and display the result

  # Ensure that the main function is called when this script is run
if __name__ == "__main__":
    main()

