# -*- coding: utf-8 -*-
"""04_pythagorean_theorem.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wKvuczHyzNqJTuewjSAA80aSlHMhWvrz
"""

import math # to use sqrt for calculating the hypotenuse

def main():
  # get the  two lengths from the user
   ab = float(input("Enter the length of AB: "))
   ac = float(input("Enter the length of AC: "))

  # calculate that the main function is called when this script is run
   print("The length of BC (the hypotenuse) is:", math.sqrt(ab**2 + ac**2))

  # Ensure  that the main function is called when this script is run
if __name__ == "__main__":
  main()