# -*- coding: utf-8 -*-
"""06_rolldice.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ml0lL1mXAKORkZZfSWxjB7_ePaZlyGpE
"""

import random

def main():
    # Roll two dice (each between 1 and 6)
    die1 = random.randint(1, 6)
    die2 = random.randint(1, 6)

    # Calculate the total of the dice rolls
    total = die1 + die2

    # Print the results in the same format as your original request
    print(f"Dice have 6 sides each.")
    print(f"First die: {die1}")
    print(f"Second die: {die2}")
    print(f"Total of two dice: {total}")

# Run the main function
if __name__ == '__main__':
    main()