# -*- coding: utf-8 -*-
"""07_tiny_mad_lib.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UVItUnDQtpckCUpXHWqU8PRf-oX8t8gr
"""

# Constant for the sentence starter
SENTENCE_START: str = "Panaversity is fun. I learned to program and used Python to make my "

def main():
      # Get the three inputs from the user to make the adlib
       adjective: str = input("Enter an adjective: ")
       noun: str = input("Enter a noun: ")
       verb: str = input("Enter a verb: ")

       # Join the inputs together with the sentence starter
       print(SENTENCE_START + adjective + " " + noun + " " + verb + "!")

# This provided line is required at the end of the Python file to call the main() function.
if __name__ == '__main__':
    main()