# -*- coding: utf-8 -*-
"""01_add_many_number.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J_JFDdCMx0Yo4pvXT-f0PfnynCLVfRSz
"""

def add_many_numbers(numbers) -> int:
    """
    Takes in a list of numbers and returns the sum of those numbers.
    """
    total_so_far: int = 0
    # Loop through each number in the list and add to the total
    for number in numbers:
        total_so_far += number

    return total_so_far

def main():
    # Create a list of numbers
    numbers: list[int] = [1, 2, 3, 4, 5]

    # Call the function to get the sum of the numbers
    sum_of_numbers: int = add_many_numbers(numbers)

    # Print the result
    print("The sum of the numbers is:", sum_of_numbers)

# This provided line is required at the end of the Python file to call the main() function.
if __name__ == '__main__':
    main()