# -*- coding: utf-8 -*-
"""02_double_list.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ypwb0CtSnQcAVVhnQavnJlvJigbbeMWL
"""

def main():
    # Initial list of numbers
    numbers: list[int] = [1, 2, 3, 4]  # Example list of numbers

    # Loop through each element in the list using its index
    for i in range(len(numbers)):  # Loop through the indices of the list
        numbers[i] = numbers[i] * 2  # Double the element at index i

    # Print the modified list
    print(numbers)  # This should print the doubled list


# This provided line is required at the end of the Python file to call the main() function.
if __name__ == '__main__':
    main()