# -*- coding: utf-8 -*-
"""04_flowing_with_data_structures.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZvOdVm8rOdhaRCK_FTNLd_fdrKw7duCG
"""

# Function that adds three copies of the provided data to the given list
def add_three_copies(my_list, data):
    """
    This function takes a list 'my_list' and some data 'data'.
    It adds three copies of the 'data' to the list 'my_list'.
    The function modifies the list in place and does not return anything.
    """
    # Add 'data' three times to the list
    for i in range(3):
        my_list.append(data)  # Append data to the list

# The main function where the program starts execution
def main():
    # Prompt the user to input a message that they want to copy
    message = input("Enter a message to copy: ")

    # Create an empty list that will hold the copies of the message
    my_list = []

    # Print the list before calling the function (It should be empty)
    print("List before:", my_list)

    # Call the function to add three copies of the message to the list
    add_three_copies(my_list, message)

    # Print the list after calling the function (It should have three copies of the message)
    print("List after:", my_list)

# This block ensures that the main() function is called when the script is run
if __name__ == "__main__":
    main()