# -*- coding: utf-8 -*-
"""06_get_last_element.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ekJ-HgkEwWZq8CW4jOiZ_cM9L26Lezs4

**06_get_last_element.md**
"""

def get_last_element(lst):
    """
    Prints the last element of the provided list.
    """
    print(lst[-1])  # Prints the last element using negative index

def get_lst():
    """
    Prompts the user to enter one element of the list at a time and returns the resulting list.
    """
    lst = []  # Initialize an empty list
    while True:
        elem = input("Please enter an element of the list (or press enter to stop): ")
        if elem == "":  # Stop input when the user presses enter without typing anything
            break
        lst.append(elem)  # Add the element to the list
    return lst  # Return the completed list

def main():
    lst = get_lst()  # Get the list of elements from the user
    get_last_element(lst)  # Print the last element of the list

# This line ensures the main function is called when the script is run directly
if __name__ == '__main__':
    main()