# -*- coding: utf-8 -*-
"""07_get_list.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ht6QDWx1pHqozZ3krB9_J_AgO7EC-yjY

**07_get_list.md**
"""

def main():
  lst = []   # Create an empty list


  while True:
    val = input("Enter a value: ")  #Prompt the user to enter a value
    if val == "":   # if the input is an emptystring, break the loop
      break
    lst.append(val)     # Add the value to the list

  print("Here's the list:", lst)  # Print the list after the loop ends


# This line makes sure the main function when the script is executed

if __name__ == "__main__":
    main()