# -*- coding: utf-8 -*-
"""08_shorten.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qnUeBTC9nsx2mW3tyW32b6WqesNdPEZM

**08_shorten.md**
"""

MAX_LENGTH = 3  # tHE MAXIMUN LENGTH OF THE LIST

def shorten(lst):

  """
    Removes elements from the end of the list until it is MAX_LENGTH long,
    and prints each item it removes.
    """

    # While the list length is greater that the allowed MAX_LENGTH, keep removing from the end
  while len(lst) > MAX_LENGTH:
      last_elem = lst.pop()  # remove the last element from the last
      print(last_elem)  #print the removed element

def get_lst():

     """
    Prompts the user to enter one element of the list at a time and returns the list.
    """
     lst = [] #  initialize an empty list
     while True:
        elem = input("Please enter an element of the list or press enter to stop: ")
        if elem == "":
            break
        lst.append(elem)
     return lst      # Return the list

def main():
    lst = get_lst()  # Get the list from the user
    shorten(lst)  # Shorten the list and print removed elements

if __name__ == "__main__":
    main()  # Call the main function to run the program

"""Another way of solve code."""

MAX_LENGTH : int = 3

def shorten(lst):
    while len(lst) > MAX_LENGTH:
        last_elem = lst.pop()
        print(last_elem)

# There is no need to edit code beyond this point

def get_lst():
    """
    Prompts the user to enter one element of the list at a time and returns the resulting list.
    """
    lst = []
    elem = input("Please enter an element of the list or press enter to stop. ")
    while elem != "":
        lst.append(elem)
        elem = input("Please enter an element of the list or press enter to stop. ")
    return lst

def main():
    lst = get_lst()
    shorten(lst)


if __name__ == '__main__':
    main()