# -*- coding: utf-8 -*-
"""00_count_nums.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SevfRenQYvZxp9fe9wY45uzTQOXZ3zpD

04_dictionaries
# 00_count_nums.md
"""

def main():
    # Initialize an empty dictionary to store the count of each number
    count_dict = {}

    # Infinite loop to continuously ask for user input
    while True:
        try:
            # Ask the user for a number
            num = int(input("Enter a number: "))

            # If the number is already in the dictionary, increment its count
            if num in count_dict:
                count_dict[num] += 1
            else:
                count_dict[num] = 1

        except ValueError:
            print("Invalid input. Please enter a valid number.")

        # Ask if they want to stop entering numbers
        more_input = input("Do you want to enter another number? (yes/no): ").strip().lower()
        if more_input != 'yes':
            break

    # Display the results
    for number, count in count_dict.items():
        print(f"{number} appears {count} times.")

# This provided line is required at the end of
# Python file to call the main() function.
if __name__ == '__main__':
    main()