# -*- coding: utf-8 -*-
"""01_phonebook.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q9f7f--ubP6vsrN6sB4rff9pch1oYi5-

# 04_dictionaries

01_phonebook.md
"""

def main():
    # Initialize an empty dictionary for the phonebook
    phonebook = {}

    while True:
        # Display the menu options to the user
        print("\nPhonebook Menu:")
        print("1. Add a new contact")
        print("2. Search for a contact")
        print("3. Display all contacts")
        print("4. Exit")

        # Get the user's choice
        choice = input("Enter your choice (1-4): ")

        if choice == '1':
            # Add a new contact
            name = input("Enter the name: ")
            phone_number = input("Enter the phone number: ")
            phonebook[name] = phone_number
            print(f"Contact for {name} added successfully.")

        elif choice == '2':
            # Search for a contact
            name = input("Enter the name to search: ")
            if name in phonebook:
                print(f"The phone number for {name} is {phonebook[name]}")
            else:
                print(f"No contact found for {name}")

        elif choice == '3':
            # Display all contacts
            if phonebook:
                print("\nAll Contacts:")
                for name, phone_number in phonebook.items():
                    print(f"{name}: {phone_number}")
            else:
                print("No contacts found in the phonebook.")

        elif choice == '4':
            # Exit the program
            print("Exiting the phonebook program.")
            break

        else:
            print("Invalid choice, please try again.")

# This provided line is required at the end of the Python file to call the main() function.
if __name__ == '__main__':
    main()