# -*- coding: utf-8 -*-
"""01_greetings.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WmlJaX2tl2089kPB7DyTaQ39EYxpD3iJ

07_information_flow
# 01_greetings.md
"""

# Define the greet function to print a greeting
def greet(name):
    print(f"Greetings {name}!")

# Main function to interact with the user
def main():
    # Prompt the user for their name
    name = input("What's your name? ")

    # Call the greet function with the user's name
    greet(name)

# This line ensures the main function is called when the script is run
if __name__ == '__main__':
    main()