# -*- coding: utf-8 -*-
"""02_in_range.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lxapkjv5oppZF-QBlGPGj_Artvm_0im3

07_information_flow
# 02_in_range.md
"""

# Define the function to check if n is in the range [low, high]
def in_range(n, low, high):
    # Return True if n is between low and high (inclusive)
    return low <= n <= high

# Main function to test the in_range function
def main():
    # Test the function with some examples
    print(in_range(5, 1, 10))  # Should return True
    print(in_range(0, 1, 10))  # Should return False
    print(in_range(10, 1, 10)) # Should return True

# This line ensures the main function is called when the script is run
if __name__ == '__main__':
    main()