# -*- coding: utf-8 -*-
"""01_print_events.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17iG75CMs0GkYXQBpAXlcS7ecr_DqbREK

# 03_if_statements    
# 01_print_events.md
"""

def main():
   # Start from 0 and add 2 each time until we reach 40 (the 20th even number)
   number = 0
   for _ in range(20): # Loop 20 times
    print(number, end=" ")  # Print the number with a space between them
    number += 2       # Increment the number by 2 to get the next even number

# Call the main function when the program runs
if __name__ == "__main__":
   main()

"""ANOTHER WAY OR EXAMPLE"""

def main():
   # This for-loop start at 0 and counts up to 19 (for a total of 20 numbers)
   for i in range(20):
      print(i * 2)  # use the 'i' value inside the for-loop

if __name__ == "__main__":
    main()