# -*- coding: utf-8 -*-
"""03_leap_year.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dXsKUHRcmwWwWagMSGaTTo0TES04x2Ae
"""

def main():
    # Get the year from the user input
    year = int(input("Please input a year: "))

    # Check for leap year based on the given conditions
    if year % 4 == 0:
        if year % 100 == 0:
            if year % 400 == 0:
                print("That's a leap year!")
            else:
                print("That's not a leap year.")
        else:
            print("That's a leap year!")
    else:
        print("That's not a leap year.")


# This ensures the main() function is called when the script is executed
if __name__ == '__main__':
    main()