# -*- coding: utf-8 -*-
"""05_random_numbers.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RlouQE2reeQyMZPnOsABIT8V0Z-gCD2m

03_if_statements
# 05_random_numbers.md
"""

import random

N_NUMBERS = 10
MIN_VALUE = 1
MAX_VALUE = 100

def main():
    # Generate and print 10 random numbers between MIN_VALUE and MAX_VALUE
    random_numbers = [random.randint(MIN_VALUE, MAX_VALUE) for _ in range(N_NUMBERS)]
    print(" ".join(map(str, random_numbers)))

if __name__ == '__main__':
    main()