# -*- coding: utf-8 -*-
"""04_liftoff.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RiN5k0s7b7wncOdsuvL7WugOwjKvG4Vu

# 05_loops_control_flow
04_liftoff.md
"""

def main():
    # Countdown from 10 to 1
    for i in range(10, 0, -1):  # Starts from 10, ends at 1, decreasing by 1
        print(i)  # Print the current value on a new line
    print("Liftoff!")  # After the countdown, print Liftoff!

# This provided line is required to call the main() function
if __name__ == '__main__':
    main()

# """# Another Example"""

def main():
    # Countdown from 10 to 1
    for i in range(10, 0, -1):  # Starts from 10, ends at 1, decreasing by 1
        print(i, end=" ")  # Print the current value followed by a space
    print("Liftoff!")  # After the countdown, print Liftoff!

# This provided line is required to call the main() function
if __name__ == '__main__':
    main()