# -*- coding: utf-8 -*-
"""05_double_it.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fO4I5qW7dVHfquVI-LO2n75KwQCemtPR

# 05_loops_control_flow
05_double_it.md
"""

def main():
    # Ask the user to enter a number
    curr_value = int(input("Enter a number: "))  # Read input and convert it to an integer

    # Keep doubling the number until it is 100 or greater
    while curr_value < 100:
        curr_value = curr_value * 2  # Double the current value
        print(curr_value, end=" ")  # Print the current value on the same line

# This provided line is required to call the main() function
if __name__ == '__main__':
    main()