# -*- coding: utf-8 -*-
"""02_agreement_bot.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XvL9aCxywG1YErrfwTsKJdZ4ocxW286-
"""

def myFavourite():
    # Asking the user for their favorite animal
    favorite_animal = input("What's your favorite animal? ")

    # Responding with the favorite animal
    print(f"My favorite animal is also {favorite_animal}!")

# This provided line is required at the end of the Python file to call the main() function.
if __name__ == '__main__':
    myFavourite()