# -*- coding: utf-8 -*-
"""04_how_old_are_they.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FGh_vp3zGW4q-Z-34XEk4G-auFFi6Vsb
"""

def main():
    # Anton's age is given as 21 years old
    anton = 21

    # Beth is 6 years older than Anton, so add 6 to Anton's age to get Beth's age
    beth = anton + 6

    # Chen is 20 years older than Beth, so add 20 to Beth's age to get Chen's age
    chen = beth + 20

    # Drew is as old as Chen's age plus Anton's age, so add them together
    drew = chen + anton

    # Ethan is the same age as Chen, so set Ethan's age equal to Chen's age
    ethan = chen

    # Print out all of the ages!
    print(f"Anton is {anton}")
    print(f"Beth is {beth}")
    print(f"Chen is {chen}")
    print(f"Drew is {drew}")
    print(f"Ethan is {ethan}")

# There is no need to edit code beyond this point
if __name__ == '__main__':
    main()