# -*- coding: utf-8 -*-
"""05_triangle_perimeter.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v_Tr-Co6dIYvZjEJLSrgCqhkaCzG_kU_
"""

def main():
    # Get the 3 side lengths of the triangle from the user
    side1: float = float(input("What is the length of side 1 of the triangle? "))
    side2: float = float(input("What is the length of side 2 of the triangle? "))
    side3: float = float(input("What is the length of side 3 of the triangle? "))

    # Calculate the perimeter (sum of the sides)
    perimeter = side1 + side2 + side3

    # Print out the perimeter of the triangle
    print(f"The perimeter of the triangle is {perimeter}")

# This provided line is required at the end of the Python file to call the main() function
if __name__ == '__main__':
    main()