# -*- coding: utf-8 -*-
"""06_square_number.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EEBs70yNrnSagO9jGdvaQmxbzAkVAHBI
"""

def main():
    # Ask the user for a number and convert it to a float
    num: float = float(input("Type a number to see its square: "))

    # Print the square of the number (num raised to the power of 2)
    print(f"{num} squared is {num ** 2}")

# This provided line is required at the end of the Python file to call the main() function
if __name__ == '__main__':
    main()